sonar.projectKey=project1
sonar.projectName=project1
sonar.language=py
sonar.token=sqp_97cdd58708bb8ea83d71acda789a34f666e21cda
sonar.host.url=http://172.25.112.1:9000
sonar.python.coverage.reportPaths=coverage.xml
sonar.sources=app.py
sonar.tests=test_app.py
